"use client";

import type { Cart, Proposal } from "@/lib/api";
import { Icon } from "./icons";
import { money, type StoreProduct } from "./types";
import { useDialog } from "./use-dialog";

export type DraftLine = { product: StoreProduct; quantity: number };
const statusText = (value: Proposal["status"]) => ({ proposed: "Ожидает подтверждения", queued: "В очереди", executing: "Добавляем", applied: "Добавлено", rejected: "Отклонено", expired: "Срок истёк", stale: "Данные изменились", failed: "Ошибка", outcome_unknown: "Статус уточняется" })[value];

export function CartDrawer({ open, onClose, ready, capability, draft, cart, proposal, busy, onQuantity, onRemove, onPropose, onConfirm, onReject, onCheck }: {
  open: boolean; onClose: () => void; ready: boolean; capability?: string; draft: DraftLine[]; cart: Cart | null; proposal: Proposal | null; busy: boolean;
  onQuantity: (id: number, quantity: number) => void; onRemove: (id: number) => void; onPropose: () => void; onConfirm: () => void; onReject: () => void; onCheck: () => void;
}) {
  const dialogRef = useDialog(open, onClose);
  if (!open) return null;
  return <div className="drawer-overlay" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><aside ref={dialogRef} className="cart-drawer" role="dialog" aria-modal="true" aria-label="Подборка и корзина"><div className="drawer-header"><div><span className="micro-label">ВАШ ЗАКАЗ</span><h2>Подборка и корзина</h2></div><button data-dialog-close onClick={onClose} aria-label="Закрыть"><Icon name="close"/></button></div><div className="drawer-body">{!ready && <div className="empty-block">Корзина не подключена. Статус API: {capability || "неизвестен"}.</div>}{ready && <>
    <div className="drawer-section"><h3>К добавлению <span>{draft.length}</span></h3>{draft.length === 0 ? <p className="drawer-empty">Добавьте товары из каталога. Предложение можно проверить перед подтверждением.</p> : draft.map(item => <div className="draft-product" key={item.product.id}><div><small>{item.product.article_original}</small><strong>{item.product.name}</strong><span>{money(item.product.price_amount, item.product.price_currency || "KZT")}</span></div><div className="draft-controls"><button onClick={() => onQuantity(item.product.id, item.quantity - 1)} disabled={item.quantity <= (item.product.min_order || 1)} aria-label="Уменьшить"><Icon name="minus" size={14}/></button><input type="number" min={item.product.min_order || 1} max="100000" aria-label={`Количество ${item.product.name}`} value={item.quantity} onChange={event => onQuantity(item.product.id, Number(event.target.value))}/><button onClick={() => onQuantity(item.product.id, item.quantity + 1)} aria-label="Увеличить"><Icon name="plus" size={14}/></button><button className="draft-remove" onClick={() => onRemove(item.product.id)} aria-label="Убрать"><Icon name="close" size={15}/></button></div></div>)}{draft.length > 0 && <button className="main-button drawer-action" disabled={busy} onClick={onPropose}>Проверить предложение <Icon name="arrow" size={17}/></button>}</div>
    {proposal && <div className="drawer-section proposal-card"><div className="proposal-card-head"><span className="micro-label">ПРЕДЛОЖЕНИЕ #{proposal.id.slice(0, 8)}</span><span className={`proposal-tag ${proposal.status}`}>{statusText(proposal.status)}</span></div><p>{proposal.mode === "demo" ? "Демонстрационная корзина" : "Корзина ЭКТ"} · Версия {proposal.cart_version}</p>{proposal.items.map(item => <div className="proposal-line" key={item.product_id}><span>{item.name}<small>{item.quantity} × {money(item.unit_price_amount, proposal.currency)}</small></span><strong>{money(item.line_total_amount, proposal.currency)}</strong></div>)}<div className="proposal-total"><span>Итого</span><strong>{money(proposal.total_amount, proposal.currency)}</strong></div><small className="proposal-expires">Действует до {new Date(proposal.expires_at * 1000).toLocaleString("ru-RU")}.</small>{proposal.status === "proposed" && <div className="proposal-buttons"><button className="main-button" disabled={busy} onClick={onConfirm}>Подтвердить добавление</button><button className="outline-button" disabled={busy} onClick={onReject}>Отклонить</button></div>}{proposal.status === "outcome_unknown" && <button className="outline-button" onClick={onCheck}>Проверить статус</button>}{["expired", "stale", "failed"].includes(proposal.status) && <p className="proposal-warning">Проверьте данные и сформируйте новое предложение.</p>}</div>}
    <div className="drawer-section current-cart"><h3>В корзине <span>{cart?.items.length || 0}</span></h3>{cart?.items.length ? cart.items.map(item => <div className="cart-line" key={item.product_id}><span>{item.name}<small>{item.quantity} × {money(item.unit_price_amount, cart.currency)}</small></span><strong>{money(item.line_total_amount, cart.currency)}</strong></div>) : <p className="drawer-empty">Корзина пуста.</p>}<div className="proposal-total"><span>Итого</span><strong>{money(cart?.total_amount || "0", cart?.currency || "KZT")}</strong></div><p className="micro-note">{cart?.mode === "demo" ? "Демо-корзина. Заказ на ekt.kz не оформляется." : "Проверьте состав перед оформлением заказа."}</p></div>
  </>}</div><div className="drawer-footer"><Icon name="shield" size={18}/> Товары добавляются только после вашего подтверждения.</div></aside></div>;
}
