"use client";
import type { FormEvent } from "react";
import { Icon } from "./icons";
import { categoryIcon } from "./product-card";
import { type Category, pathKey } from "./types";

export function StoreHeader({ section, categories, menuOpen, setMenuOpen, query, setQuery, onSearch, onHome, onCatalog, onCategory, onFavorites, onCompare, onCart, onAssistant, favorites, comparison, cartCount }: {
  section: string; categories: Category[]; menuOpen: boolean; setMenuOpen: (value: boolean) => void; query: string; setQuery: (value: string) => void; onSearch: (event: FormEvent<HTMLFormElement>) => void; onHome: () => void; onCatalog: () => void; onCategory: (category: Category) => void; onFavorites: () => void; onCompare: () => void; onCart: () => void; onAssistant: () => void; favorites: number; comparison: number; cartCount: number;
}) {
  return <><div className="utility-bar"><div className="container utility-content"><div className="utility-left"><a href="https://ekt.kz/about/contacts/" target="_blank" rel="noreferrer"><Icon name="pin" size={14}/> Алматы · контакты магазинов</a><span className="utility-sep"/><a href="tel:+77273468888"><Icon name="phone" size={14}/> +7 (727) 346-88-88</a></div><div className="utility-right"><span>Демо-витрина ассистента</span><a href="https://ekt.kz/" target="_blank" rel="noreferrer">Официальный сайт ЭКТ <Icon name="external" size={12}/></a></div></div></div>
    <header className="store-header"><div className="container header-main"><button className="brand-button" type="button" onClick={onHome} aria-label="На главную"><span className="brand-emblem"><Icon name="bolt" size={27}/></span><span className="brand-type"><b>ЭЛЕКТРО<span>КОМПЛЕКТ</span></b><small>Электротехника для ваших проектов</small></span></button><div className="search-zone"><button className={`catalog-trigger ${menuOpen ? "on" : ""}`} onClick={() => setMenuOpen(!menuOpen)} type="button" aria-expanded={menuOpen}><Icon name="menu" size={19}/> Каталог</button><form className="main-search" onSubmit={onSearch}><label className="sr-only" htmlFor="main-search">Поиск товаров</label><input id="main-search" placeholder="Поиск по каталогу, названию или артикулу" value={query} onChange={event => setQuery(event.target.value)}/><button type="submit" aria-label="Найти"><Icon name="search" size={20}/></button></form></div><div className="header-actions"><button type="button" onClick={onFavorites} className={section === "favorites" ? "active" : ""} aria-label="Избранное"><Icon name="heart"/><span>Избранное</span>{favorites > 0 && <i>{favorites}</i>}</button><button type="button" onClick={onCompare} aria-label="Сравнение"><Icon name="compare"/><span>Сравнение</span>{comparison > 0 && <i>{comparison}</i>}</button><button type="button" onClick={onCart} aria-label="Корзина"><Icon name="cart"/><span>Корзина</span>{cartCount > 0 && <i>{cartCount}</i>}</button></div></div>{menuOpen && <div className="container dropdown-wrap"><div className="category-dropdown"><div className="dropdown-title">Категории товаров <button type="button" onClick={() => setMenuOpen(false)} aria-label="Закрыть"><Icon name="close" size={18}/></button></div><div className="dropdown-grid">{categories.map(category => <button key={pathKey(category)} type="button" onClick={() => onCategory(category)}><span className="dropdown-icon"><Icon name={categoryIcon(category.name)} size={22}/></span><span>{category.name}<small>{category.count} товаров</small></span><Icon name="arrow" size={16}/></button>)}</div>{categories.length === 0 && <p className="empty-inline">Категории пока недоступны.</p>}</div></div>}</header>
    <nav className="secondary-nav"><div className="container nav-content"><button onClick={onHome} className={section === "home" ? "active" : ""}>Главная</button><button onClick={onCatalog} className={section === "catalog" ? "active" : ""}>Все товары</button><a href="https://ekt.kz/about/contacts/" target="_blank" rel="noreferrer">Контакты</a><a href="https://ekt.kz/catalog/" target="_blank" rel="noreferrer">Каталог на ekt.kz <Icon name="external" size={12}/></a><button className="nav-assistant" onClick={onAssistant}><Icon name="spark" size={16}/> Помощник по подбору</button></div></nav></>;
}
