"""Parser subprocess. Receives only private paths generated by DocumentsService."""
import csv
import json
import sys
from io import StringIO
from pathlib import Path

if sys.platform != "win32":
    import resource
    try:
        resource.setrlimit(resource.RLIMIT_AS, (512 * 1024 * 1024, 512 * 1024 * 1024))
    except (ValueError, OSError):
        # macOS не даёт опустить RLIMIT_AS ниже уже выделенного адресного пространства.
        # Там остаются лимит CPU ниже и таймаут процесса в DocumentsService.
        pass
    resource.setrlimit(resource.RLIMIT_CPU, (18, 18))

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")

MAX_TEXT = 40000
MAX_ROWS = 200
MAX_PAGES = 20


def clipped(text: str, warnings: list[str]) -> str:
    if len(text) > MAX_TEXT:
        warnings.append("Текст обрезан до 40 000 символов.")
        return text[:MAX_TEXT]
    return text


def parse(path: Path, extension: str, image_output: Path) -> dict:
    warnings: list[str] = []
    text = ""
    media_type = None
    if extension in {".txt", ".csv"}:
        raw = path.read_bytes().decode("utf-8-sig")
        if extension == ".csv":
            rows = []
            reader = csv.reader(StringIO(raw))
            for index, row in enumerate(reader):
                if index >= MAX_ROWS:
                    warnings.append("Показаны первые 200 строк CSV.")
                    break
                rows.append(" | ".join(row))
            text = "\n".join(rows)
        else:
            text = raw
    elif extension == ".pdf":
        from pypdf import PdfReader
        reader = PdfReader(str(path), strict=True)
        if reader.is_encrypted:
            raise ValueError("Encrypted PDF is unsupported")
        pages = []
        image_only_indices = []
        for index, page in enumerate(reader.pages[:MAX_PAGES]):
            page_text = page.extract_text() or ""
            pages.append(page_text)
            if len(page_text.strip()) < 30:
                image_only_indices.append(index)
        if len(reader.pages) > MAX_PAGES:
            warnings.append("Обработаны первые 20 страниц PDF.")
        text = "\n\n".join(pages)
        if image_only_indices:
            warnings.append("Страницы без извлекаемого текста передаются как изображения без OCR.")
            import pypdfium2 as pdfium
            from PIL import Image
            Image.MAX_IMAGE_PIXELS = 20_000_000
            pdf = pdfium.PdfDocument(str(path))
            selected = image_only_indices[:4]
            for image_index, index in enumerate(selected):
                page = pdf[index]
                width, height = page.get_size()
                scale = min(2000 / max(width, height), 2.5)
                bitmap = page.render(scale=scale)
                image = bitmap.to_pil().convert("RGB")
                image.save(image_output.with_name(f"{image_output.name}-{image_index}"), format="PNG", optimize=True)
                page.close()
            pdf.close()
            media_type = "image/png"
            if len(image_only_indices) > len(selected):
                warnings.append(f"Показаны первые {len(selected)} страницы без текста; остальные пропущены.")
    elif extension == ".xlsx":
        from openpyxl import load_workbook
        source = path.open("rb")
        workbook = load_workbook(source, read_only=True, data_only=True, keep_links=False)
        lines = []
        row_count = 0
        try:
            for sheet in workbook.worksheets[:20]:
                lines.append(f"Лист: {sheet.title}")
                for row in sheet.iter_rows(values_only=True):
                    if row_count >= MAX_ROWS:
                        warnings.append("Обработаны первые 200 строк таблицы.")
                        break
                    if len(row) > 50:
                        warnings.append("В строках таблицы показаны первые 50 столбцов.")
                    lines.append(" | ".join(str(value) if value is not None else "" for value in row[:50]))
                    row_count += 1
                if row_count >= MAX_ROWS:
                    break
            if len(workbook.worksheets) > 20:
                warnings.append("Обработаны первые 20 листов.")
        finally:
            workbook.close()
            source.close()
        text = "\n".join(lines)
    elif extension == ".docx":
        from docx import Document
        document = Document(str(path))
        parts = [paragraph.text for paragraph in document.paragraphs[:1000]]
        if len(document.paragraphs) > 1000:
            warnings.append("Показаны первые 1000 абзацев документа.")
        row_count = 0
        for table in document.tables[:20]:
            for row in table.rows:
                if row_count >= MAX_ROWS:
                    warnings.append("В таблицах показаны первые 200 строк.")
                    break
                if len(row.cells) > 50:
                    warnings.append("В таблицах показаны первые 50 столбцов.")
                parts.append(" | ".join(cell.text for cell in row.cells[:50]))
                row_count += 1
            if row_count >= MAX_ROWS:
                break
        if len(document.tables) > 20:
            warnings.append("Показаны первые 20 таблиц документа.")
        text = "\n".join(parts)
    elif extension in {".jpg", ".jpeg", ".png"}:
        from PIL import Image, ImageOps
        Image.MAX_IMAGE_PIXELS = 20_000_000
        with Image.open(path) as source:
            if source.width * source.height > 20_000_000:
                raise ValueError("Image exceeds 20 megapixels")
            image = ImageOps.exif_transpose(source)
            if max(image.size) > 2000:
                image.thumbnail((2000, 2000), Image.Resampling.LANCZOS)
                warnings.append("Изображение уменьшено до 2000 пикселей по длинной стороне.")
            if extension == ".png":
                image = image.convert("RGBA" if "A" in image.getbands() else "RGB")
                image.save(image_output, format="PNG", optimize=True)
                media_type = "image/png"
            else:
                image = image.convert("RGB")
                image.save(image_output, format="JPEG", quality=90, optimize=True)
                media_type = "image/jpeg"
        warnings.append("Изображение очищено от метаданных; текст не распознан.")
    else:
        raise ValueError("Unsupported extension")
    text = clipped(text, warnings)
    return {"text": text, "warnings": list(dict.fromkeys(warnings)), "status": "partial" if warnings and extension not in {".jpg", ".jpeg", ".png"} else "ready", "image_media_type": media_type}


if __name__ == "__main__":
    try:
        result = parse(Path(sys.argv[1]), sys.argv[2], Path(sys.argv[3]))
        print(json.dumps(result, ensure_ascii=False))
    except Exception as error:
        print(type(error).__name__ + ": " + str(error)[:200], file=sys.stderr)
        sys.exit(2)
