from typing import Protocol

from app.modules.chat.models import (
    AssistantOutput, ClaimedJob, ConversationView, MessageView,
    Session, TurnInput, TurnSubmission, TurnView,
)


class StateStore(Protocol):
    """Atomicity and isolation requirements are documented in docs/backend-integration.md."""
    def initialize(self) -> None: ...
    def ping(self) -> None: ...
    def consume_rate(self, bucket: str, limit: int, now: float) -> None: ...
    def create_session(self, token_hash: str, expires_at: float) -> Session: ...
    def find_session(self, token_hash: str, now: float) -> Session | None: ...
    def session_alive(self, session_id: str, now: float) -> bool: ...
    def create_conversation(self, session_id: str, now: float, limit: int) -> ConversationView: ...
    def conversation_owned(self, session_id: str, conversation_id: str) -> None: ...
    def messages(self, session_id: str, conversation_id: str, limit: int) -> list[MessageView]: ...
    def replay(self, session_id: str, conversation_id: str, key: str,
               payload: TurnInput) -> TurnSubmission | None: ...
    def submit(self, session_id: str, conversation_id: str, key: str, payload: TurnInput,
               now: float, max_pending: int, max_turns: int) -> TurnSubmission: ...
    def get_turn(self, session_id: str, turn_id: str) -> TurnView: ...
    def cancel(self, session_id: str, turn_id: str, now: float) -> TurnView: ...
    def claim(self, now: float, lease_seconds: int) -> ClaimedJob | None: ...
    def active(self, job: ClaimedJob, now: float) -> bool: ...
    def finish(self, job: ClaimedJob, output: AssistantOutput | None,
               error_code: str | None, now: float) -> bool: ...
    def cleanup(self, now: float) -> None: ...
